#  ___________________________________________________
# |  _____                       _____ _ _       _    |
# | |  __ \                     |  __ (_) |     | |   |
# | | |__) |__ _ __   __ _ _   _| |__) || | ___ | |_  |
# | |  ___/ _ \ '_ \ / _` | | | |  ___/ | |/ _ \| __| |
# | | |  |  __/ | | | (_| | |_| | |   | | | (_) | |_  |
# | |_|   \___|_| |_|\__, |\__,_|_|   |_|_|\___/ \__| |
# |                   __/ |                           |
# |  GNU/Linux based |___/  Multi-Rotor UAV Autopilot |
# |___________________________________________________|
#
# System Parameters Configuration File
#
# Copyright (C) 2014 Tobias Simon, Integrated Communication Systems Group, TU Ilmenau
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.


overo_quad: # Gumstix Overo based quadrotor
   mass: 1.1 # Kg
   thrust_max: 40.0 # N
   motors:
      driver: 'omap3_pwm'
      f2e: 'hk20_roxxy282735_1045'
      n_motors: 4
      mot_1: 8
      mot_2: 10
      mot_3: 11
      mot_4: 9
   voltage_channel: 7 # TWL4030_MADC
   current_channel: 2 # TWL4030_MADC
   adc_to_voltage: 'lambda x: (x + 27.0951) / 117.1319'
   adc_to_current: 'lambda x: 0.0303 * (2500 - x) + 0.4'
   rx_type: 'sbus' # 'sbus' or 'dsl'
   sbus_serial: # taranis sbus
      path: '/dev/ttyO0'
   dsl_serial: # ACT dsl
      path: '/dev/ttyO0'
      speed: 38400
   gpsp_serial: # GPS publisher
      path: "/dev/ttyO2"
      speed: 115200
   nrf_serial: "/dev/ttyACM0"

pi_quad: # Raspberry PI based quadrotor
   mass: 1.1 # Kg
   thrust_max: 40.0 # N
   voltage_channel: 0 # currently ignored
   current_channel: 1 # currently ignored
   adc_to_voltage: 'lambda x : x * 0.003 * 3.6045'
   adc_to_current: 'lambda x : x'
   rx_type: 'dsl'
   dsl_serial: # ACT DSL
      path: '/dev/ttyAMA0'
      speed: 38400
   nrf_serial: "/dev/ttyACM0"


exynos_quad: # ODROID U3 based quadrotor
   mass: 1.1
   thrust_max: 40.0 # N
   rx_type: 'dsl'
   arduino_serial: # U3 IO shield serial interface
      path: '/dev/ttySAC0'
      speed: 115200
   gpsp_serial: # GPS publisher
      path: "/dev/gps0" # created by udev rule
      speed: 115200
   nrf_serial: "/dev/nrf0" # created by udev rule
   motors:
      driver: 'arduino'
      f2e: 'hk20_roxxy282735_1045'
      n_motors: 4
      order: '1, 4, 3, 2'
   marg:
      rot_quat: # marg orientation with reference to uav
         x: 0.0
         y: 0.0
         z: 1.0
         w: 135.0 # degrees
      mag:
         rot_quat: # magnetometer orientation with reference to marg platform
            x: 0.0
            y: 0.0
            z: 1.0
            w: 0.0
 
aircomm:
   id: 1
   psk: "This is the PenguPilot Standard Pre-Shared Key for NRF24L01+ Communication"

battmon:
   cells: 4
   low_cell_voltage_idle: 3.6 # [V]
   low_cell_voltage_load: 3.4 # [V]
   current_treshold: 3.0 # [A]
   low_voltage_hysteresis: 10.0 # [s], battery needs to go below battery_low_cell_voltage for this time period in order to trigger a low power event
 

acc_cal: # accelerometer calibration
   acc_bias_x: 0.0
   acc_bias_y: 0.0
   acc_bias_z: 0.0
   acc_scale_x: 1.0
   acc_scale_y: 1.0
   acc_scale_z: 1.0


mag_adc_cal: # magnetometer calibration data
   mag_bias_x: 0.0
   mag_bias_y: 0.0
   mag_bias_z: 0.0
   mag_scale_x: 1.0
   mag_scale_y: 1.0
   mag_scale_z: 1.0


cmc: # current magnetometer calibration
   bias: 0.0
   scale_x: 0.0
   scale_y: 0.0
   scale_z: 0.0


rc_cal:
   pitch:
      index: -1
      min: -1.0
      max: 1.0
   roll:
      index: -1
      min: -1.0
      max: 1.0
   yaw:
      index: -1
      min: -1.0
      max: 1.0
   gas:
      index: -1
      min: -1.0
      max: 1.0
   two_state:
      index: -1
      min: -1.0
      max: 1.0
   three_state:
      index: -1
      min: -1.0
      max: 1.0


logger:
   level: 3
   details: 2


ahrs: # attitude and heading reference system
   p_start: 20.0
   p_step: 0.01
   p_end: 0.05
   i: 0.001


mixer: # enables different parts of the coupling matrix
   imtx1: 1575696.45783 # gas column of matrix is multiplied with this
   imtx2: 15562434.1515 # pitch and roll columns of matrix are multiplied with this
   imtx3: 62229302.534  # yaw column is multiplied with this
   f_c: 1.5866e-007
   quad_matrix: '1.0,  1.0,   0.0, -1.0,
                 1.0, -1.0,   0.0, -1.0,
                 1.0,  0.0,   1.0,  1.0,
                 1.0,  0.0,  -1.0,  1.0'
               # gas   pitch  roll  yaw

rs_ctrl: # basic stabilizing controller:
   att_kd: 0.03929356367277829
   att_ki: 5.216018377845929
   att_kii: 1.9043325795347907
   att_kp: 0.36397715175895795
   yaw_kd: 0.0009970913130018957
   yaw_ki: 3.531770730332799
   yaw_kii: 3.8199155415521995
   yaw_kp: 0.35127751586656414
   filt_fg: 10.0
   filt_d: 0.95
   jxx_jyy: 0.0097
   jzz: 0.0057292965
   tmc: 0.03


rp_ctrl:
   pr_p: 6.226615273654109
   pr_d: 0.5402391324294383
   yaw_p: 4.0
   pitch_bias: 0.0
   roll_bias: 0.0
   angles_max: 40.0 # maximal angle allowed in attitude control

vs_ctrl: # vertical speed control
   max_speed: 3.0
   p: 4.0
   i: 2.0
   max_sum_err: 2.0

vp_ctrl: # vertical position control
   p: 1.0


hs_ctrl: # horizontal speed control
   p: 0.3
   i: 0.2
   max_sum_err: 2.0
   angles_max: 15.0

hp_ctrl: # horizontal position control
   p: 0.1


sticks:
   pitch_roll_speed_max: 180.0 # [deg/s]
   pitch_roll_angle_max: 35.0 # [deg]
   vert_speed_max: 1.5
   horiz_speed_max: 5.0 # maximal horizontal speed
   horiz_deadzone: 0.05 # deadzone for angle and gps control
   vert_deadzone: 0.15 # if magnitude of centered gas stick is lower than this value, altitude is locked
   yaw_speed_max: 90.0 # maximum yaw rotation speed [deg/s]
   yaw_deadzone: 0.02 # yaw deadzone
   gas_acc_max: 20.0 # maximum positive/negative acceleration in m/s^2
   rotation: 0.0 # 0 = "+" mode, 90 = "x mode"
   expo: 6.0


pos_speed_est_neu: # NEU position estimate kalman filter
   process_noise: 1.0e-6
   baro_noise: 0.01
   ultra_noise: 0.01
   gps_noise: 0.01
   use_gps_speed: 0 # use gps speed to correct estimate?


autopilot:

   main:
      acc_fg: 0.03 # accelerometer low-pass filter

   cmc: # current magnetometer calibration
      bias: 0.0
      scale_x: 0.0
      scale_y: 0.0
      scale_z: 0.0

   sticks:
      pitch_roll_speed_max: 180.0 # [deg/s]
      pitch_roll_angle_max: 35.0 # [deg]
      vert_speed_max: 1.5
      horiz_speed_max: 5.0 # maximal horizontal speed
      horiz_deadzone: 0.05 # deadzone for angle and gps control
      vert_deadzone: 0.15 # if magnitude of centered gas stick is lower than this value, altitude is locked
      yaw_speed_max: 90.0 # maximum yaw rotation speed [deg/s]
      yaw_deadzone: 0.02 # yaw deadzone
      gas_acc_max: 20.0 # maximum positive/negative acceleration in m/s^2
      rotation: 0.0 # 0 = "+" mode, 90 = "x mode"
      expo: 6.0

   controllers:

     
      ne_speed: # north-east speed controller
         p: 2.581019276508608
         i: 1.827463461175307
         i_max: 10.0
         d: 0.0
         lpfg: 50.0

      attitude:
         p: 6.226615273654109
         i: 0.8956642009989297
         i_max: 10.0
         d: 0.5402391324294383
         pitch_bias: 0.0
         roll_bias: 0.0
         angles_max: 40.0 # maximal angle allowed in attitude control
   
      u_speed: # up speed controller (barometer)
         i: 2.0
         imax: 4.0
         p: 7.0
      
      u_pos: # ups position controller (barometer, ultrasonic)
         d: 15.563081600990635
         i: 15.563081600990635
         imax: 20.0
         p: 30.563081600990635
         lpfg: 15.0

      yaw: # yaw position controller
         pid_lim: 2.0
         p: 5.0
         d: 0.0
         i: 0.01
         i_max: 0.5

      navigation: # north-east position controller
         speed_min: 0.5
         speed_std: 2.0
         speed_max: 3.5
         sqrt_shift: 4.0
         sqrt_scale: 0.25
         square_shift: 0.2
         pos_i: 0.015
         pos_i_max: 5.0
         ortho_p: 0.0


